name: Rector

on:
  pull_request:
    branches:
      - '*'
  workflow_dispatch:
    branches:
      - '*'

jobs:
  rector:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, xml, tokenizer, curl, json
          tools: composer
          coverage: none

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Cache Rector cache
        uses: actions/cache@v4
        with:
          path: .rector.cache
          key: ${{ runner.os }}-rector-${{ hashFiles('**/rector.php') }}
          restore-keys: ${{ runner.os }}-rector-

      - name: Run Rector
        run: |
          vendor/bin/rector process --ansi

      - uses: EndBug/add-and-commit@v5.1.0
        with:
          add: .
          message: "[ci-review] Rector Rectify"
          author_name: "GitHub Action"
          author_email: "action+rector@github.com"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
